name: Terraform Azure Landing Zone Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Terraform Environment"
        required: true
        type: choice
        options:
          - hub
          - dev
          - uat
          - prod

jobs:
  terraform:
    name: Terraform Deploy - ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.event.inputs.environment }}

    permissions:
      contents: read

    defaults:
      run:
        working-directory: environments/${{ github.event.inputs.environment }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

     # - name: Terraform Format Check
      #  run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -var-file="${{ github.event.inputs.environment }}.tfvars" \
            -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
